# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['crinometro_laucher.py'],
    pathex=['M:\\Documentos\\Faculdade\\Biologia'],
    binaries=[],
    datas=[
        ('loading.mp4', '.'),
        ('loaded.mp4', '.'),
        ('grilinho.ico', '.'),
        ('grilinho.png', '.'),
        ('crinometro_config.json', '.'),
        ('modelo_treinado.pkl', '.'),
        ('crinometro.py', '.'),
    ],
    hiddenimports=[
        'crinometro',
        'scipy',
        'scipy.io',
        'scipy.io.wavfile',
        'scipy.special',
        'scipy.integrate',
        'scipy.signal',
        'scipy.stats',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.figure',
        'matplotlib.patches',
        'numpy',
        'sklearn',
        'sklearn.ensemble',
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PyQt6'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Crinômetro_v3.4.4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='grilinho.ico',
)
